items = ['Traceback (most recent call last):', 'File "/opt/puffer/src/portal/manage.py", line 15, in <module>',
         'execute_from_command_line(sys.argv)', 'File "/users/krish133/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line',
         'utility.execute()', 'File "/users/krish133/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute', 'settings.INSTALLED_APPS',
         'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__', 'self._setup(name)',
         'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup', 'self._wrapped = Settings(settings_module)',
         'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__', 'mod = importlib.import_module(self.SETTINGS_MODULE)',
         'File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module', 'return _bootstrap._gcd_import(name[level:], package, level)', 'File "<frozen importlib._bootstrap>", line 994, in _gcd_import',
         'File "<frozen importlib._bootstrap>", line 971, in _find_and_load', 'File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked', 'File "<frozen importlib._bootstrap>", line 665, in _load_unlocked',
         'File "<frozen importlib._bootstrap_external>", line 678, in exec_module', 'File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed',
         'File "/opt/puffer/src/portal/portal/settings.py", line 45, in <module>', "SECRET_KEY = os.environ[portal_config['secret_key']]", 'File "/usr/lib/python3.6/os.py", line 669, in __getitem__',
         'raise KeyError(key) from None', "KeyError: 'PUFFER_PORTAL_SECRET_KEY'", 'retrieve_expt_id: missing environment variable: PUFFER_PORTAL_DB_KEY', 'Running experiment -1 on 1 servers',
         '[11683] /opt/puffer/src/media-server/ws_media_server /opt/puffer/src/../src/puffer_settings.yml 1 -1',
         '[11684] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/server_info.conf /opt/puffer/src/monitoring/server_info.1.log', '[11685] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/active_streams.conf /opt/puffer/src/monitoring/active_streams.1.log', '[11686] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/client_buffer.conf /opt/puffer/src/monitoring/client_buffer.1.log', '[11687] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/client_sysinfo.conf /opt/puffer/src/monitoring/client_sysinfo.1.log', '[11688] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/video_sent.conf /opt/puffer/src/monitoring/video_sent.1.log', '[11689] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/video_acked.conf /opt/puffer/src/monitoring/video_acked.1.log', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  ProcessManager: PID 11689 exits abnormally', '', 'DevTools listening on ws://127.0.0.1:10001/devtools/browser/401de060-3e13-40b4-9dff-f0b9541a5e20', '[1028/151936.223212:ERROR:devtools_http_handler.cc(292)] Error writing DevTools active port to file', '[1028/151936.238638:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is']

The output is: ['Traceback (most recent call last):', 'File "/opt/puffer/src/portal/manage.py", line 15, in <module>',
                'execute_from_command_line(sys.argv)', 'File "/users/krish133/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line',
                'utility.execute()', 'File "/users/krish133/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute', 'settings.INSTALLED_APPS',
                'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__', 'self._setup(name)',
                'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup', 'self._wrapped = Settings(settings_module)',
                'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__', 'mod = importlib.import_module(self.SETTINGS_MODULE)',
                'File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module', 'return _bootstrap._gcd_import(name[level:], package, level)', 'File "<frozen importlib._bootstrap>", line 994, in _gcd_import',
                'File "<frozen importlib._bootstrap>", line 971, in _find_and_load', 'File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked',
                'File "<frozen importlib._bootstrap>", line 665, in _load_unlocked', 'File "<frozen importlib._bootstrap_external>", line 678, in exec_module',
                'File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed', 'File "/opt/puffer/src/portal/portal/settings.py", line 45, in <module>',
                "SECRET_KEY = os.environ[portal_config['secret_key']]", 'File "/usr/lib/python3.6/os.py", line 669, in __getitem__', 'raise KeyError(key) from None',
                "KeyError: 'PUFFER_PORTAL_SECRET_KEY'", 'retrieve_expt_id: missing environment variable: PUFFER_PORTAL_DB_KEY', 'Running experiment -1 on 1 servers',
                '[12075] /opt/puffer/src/media-server/ws_media_server /opt/puffer/src/../src/puffer_settings.yml 1 -1', '[12076] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/server_info.conf /opt/puffer/src/monitoring/server_info.1.log', '[12077] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/active_streams.conf /opt/puffer/src/monitoring/active_streams.1.log', '[12078] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/client_buffer.conf /opt/puffer/src/monitoring/client_buffer.1.log', '[12079] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/client_sysinfo.conf /opt/puffer/src/monitoring/client_sysinfo.1.log', '[12080] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/video_sent.conf /opt/puffer/src/monitoring/video_sent.1.log', '[12081] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/video_acked.conf /opt/puffer/src/monitoring/video_acked.1.log', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", "terminate called after throwing an instance of 'std::runtime_error'", 'what():  ProcessManager: PID 12076 exits abnormally', '', 'DevTools listening on ws://127.0.0.1:10001/devtools/browser/f965433f-7c52-492e-88ff-94187433a80d', '[1028/152845.472060:ERROR:devtools_http_handler.cc(292)] Error writing DevTools active port to file', '[1028/152845.489369:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is']


The output is: ['Traceback (most recent call last):', 'File "/opt/puffer/src/portal/manage.py", '
                                                      'line 15, in <module>', 'execute_from_command_line(sys.argv)',
                'File "/users/krish133/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line',
                'utility.execute()', 'File "/users/krish133/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute',
                'settings.INSTALLED_APPS', 'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__', 'self._setup(name)',
                'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup', 'self._wrapped = Settings(settings_module)',
                'File "/users/krish133/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__', 'mod = importlib.import_module(self.SETTINGS_MODULE)',
                'File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module', 'return _bootstrap._gcd_import(name[level:], package, level)', 'File "<frozen importlib._bootstrap>"'
                                                                                                                                                              ','
                   line 994, in _gcd_import', 'File "<frozen importlib._bootstrap>",
                                                    line 971, in _find_and_load', 'File "<frozen importlib._bootstrap>", line 955,
in _find_and_load_unlocked', 'File "<frozen importlib._bootstrap>", line 665, in _load_unlocked', 'File "<frozen importlib._bootstrap_external>",
                                                                                                        line 678, in exec_module', 'File "<frozen importlib._bootstrap>",
                                                                                                                                         line 219, in _call_with_frames_removed', 'File "/opt/puffer/src/portal/portal/settings.py", line 45, in <module>', "SECRET_KEY = os.environ[portal_config['secret_key']]", 'File "/usr/lib/python3.6/os.py", line 669, in __getitem__', 'raise KeyError(key) from None', "KeyError: 'PUFFER_PORTAL_SECRET_KEY'", 'retrieve_expt_id: missing environment variable: PUFFER_PORTAL_DB_KEY', 'Running experiment -1 on 1 servers', '[13217] /opt/puffer/src/media-server/ws_media_server /opt/puffer/src/../src/puffer_settings.yml 1 -1', '[13218] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/server_info.conf /opt/puffer/src/monitoring/server_info.1.log', '[13219] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/active_streams.conf /opt/puffer/src/monitoring/active_streams.1.log', '[13220] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/client_buffer.conf /opt/puffer/src/monitoring/client_buffer.1.log', '[13221] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/client_sysinfo.conf /opt/puffer/src/monitoring/client_sysinfo.1.log', '[13222] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/video_sent.conf /opt/puffer/src/monitoring/video_sent.1.log', '[13223] /opt/puffer/src/monitoring/log_reporter /opt/puffer/src/../src/puffer_settings.yml /opt/puffer/src/monitoring/video_acked.conf /opt/puffer/src/monitoring/video_acked.1.log', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  missing environment variable: INFLUXDB_PASSWORD', "terminate called after throwing an instance of 'std::runtime_error'", 'what():  ProcessManager: PID 13223 exits abnormally', '', 'DevTools listening on ws://127.0.0.1:10001/devtools/browser/0bb4d173-414f-4ae8-b051-f857a6343e86', '[1028/154647.734000:ERROR:devtools_http_handler.cc(292)] Error writing DevTools active port to file', '[1028/154647.747727:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is']
